// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { defineConfig } from 'tsup';

export function tsup() {
  return defineConfig(
      {
    "bundle": false,
    "clean": true,
    "dts": true,
    "entry": [
      "src/**/*.ts"
    ],
    "format": [
      "cjs",
      "esm"
    ],
    "minify": false,
    "outDir": "lib",
    "shims": true,
    "sourcemap": true,
    "splitting": false
  }
  );
}
