// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { defineConfig } from 'vitest/config';

export default defineConfig(
    {
    "test": {
      "clearMocks": true,
      "coverage": {
"provider": "v8",
"reporter": [
  "cobertura",
  "text",
  "html",
  "clover",
  "json"
],
"thresholds": {
  "lines": 89,
  "functions": 88,
  "branches": 87,
  "statements": 89
},
"exclude": [
  ".projenrc.ts",
  "**/*.d.ts",
  "examples",
  "lib",
  "scripts",
  "src/cli",
  "src/scripts",
  "src/utils/test"
]
      },
      "exclude": [
".cache",
".git",
".idea",
"dist",
"lib",
"node_modules"
      ],
      "globals": true,
      "silent": true,
      "watch": false
    }
  }
);
