name: release
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    env:
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure git
        run: |
          # Get author info from the most recent commit
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')

          echo "Setting git config to: $AUTHOR_NAME <$AUTHOR_EMAIL>"
          git config user.name "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build packages
        run: npx turbo build
      - name: Version packages
        run: |
          # Apply version changes and commit them
          npx changeset version
          git add .
          git commit -m "chore: release packages" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish packages
        run: |
          # Publish packages directly
          pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create GitHub Release
        run: |
          # Get the version from package.json
          PACKAGE_VERSION=$(node -p "require('./packages/client/package.json').version")
          PACKAGE_NAME=$(node -p "require('./packages/client/package.json').name")
          echo "Creating GitHub release for $PACKAGE_NAME@$PACKAGE_VERSION"
          gh release create "$PACKAGE_NAME@$PACKAGE_VERSION" --title "$PACKAGE_NAME@$PACKAGE_VERSION" --generate-notes || echo "Release may already exist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
